# Daily notes
alias openDailyNote="/home/$USER/Documents/DailyNotes/bin/openDailyNote.sh /home/$USER/Documents/DailyNotes"
alias dailyNotePath="/home/$USER/Documents/DailyNotes/bin/dailyNotePath.sh /home/$USER/Documents/DailyNotes"
alias taskUnBlocked="task +UNBLOCKED next"
alias taskFocused="task +UNBLOCKED -Unnecessary next"
