" Variable Settings
" Syntax
syntax on

" Line settings
set lbr
set number

" Shifting
set shiftround
set shiftwidth=2
" End Variable Settings

" Non-Leader Key Mappings
" Line Movements
noremap - ddp
noremap _ ddkkp
" Uppercase a word in different modes
inoremap <c-u> <esc>viwUi
nnoremap <c-u> viwU<esc>
" End Non-Leader Key Mappings

" Leader Key Mappings
let mapleader = ","
" Example Leader Key Mapping
nnoremap <localleader>d dd
" End Leader Key Mappings
