" Variable Settings
" Syntax
syntax on

" Line settings
set lbr
set number

" Shifting
set shiftround
set shiftwidth=2
" End Variable Settings

" Non-Leader Key Mappings
" Line Movements
nnoremap - ddp
nnoremap _ ddkkp
" Uppercase a word in different modes
inoremap <c-u> <esc>viwUi
nnoremap <c-u> viwU<esc>
" End Non-Leader Key Mappings

" Leader Key Mappings
let mapleader = ","
" Making it easier to make it easier to edit text
" Edit my Vimrc
:nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" Source my Vimrc
:nnoremap <leader>sv :source $MYVIMRC<cr>
" End Leader Key Mappings

" Local Leader Key Mappings
let maplocalleader = "\\"
" End Local Leader Key Mappings
